name: Renovate
on:
  schedule:
    - cron: '15 * * * *'
  workflow_dispatch:
    inputs:
      log-level:
        default: info
        type: choice
        options:
          - fatal
          - error
          - warn
          - info
          - debug

jobs:
  renovate:
    permissions:
      statuses: write
      actions: write
      contents: write
      id-token: write
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.2.0
        env:
          RENOVATE_REPOSITORIES: '["${{ github.repository }}"]'
          LOG_LEVEL: "${{inputs.log-level || 'info'}}"
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
